/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 1
 *
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "AssinaturaArrayType".
 */
export type AssinaturaArrayType = [
  {
    Assinatura: AssinaturaType;
  },
  ...{
    Assinatura: AssinaturaType;
  }[]
];

export interface BoletimTypesSchema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "CabecalhoType".
 */
export interface CabecalhoType {
  Instituicao: InstituicaoType;
  IdentificadorDocumento: string;
  Emitente?: string;
  DataEmissao: string;
}
export interface InstituicaoType {
  Nome: string;
  CNPJ: string;
  Unidade?: string;
  Endereco: EnderecoType;
  Contato?: ContatoType;
}
export interface EnderecoType {
  Logradouro: string;
  Numero: string;
  Complemento?: string;
  Bairro: string;
  Cidade: string;
  UF:
    | "AC"
    | "AL"
    | "AM"
    | "AP"
    | "BA"
    | "CE"
    | "DF"
    | "ES"
    | "GO"
    | "MA"
    | "MG"
    | "MS"
    | "MT"
    | "PA"
    | "PB"
    | "PE"
    | "PI"
    | "PR"
    | "RJ"
    | "RN"
    | "RO"
    | "RR"
    | "RS"
    | "SC"
    | "SE"
    | "SP"
    | "TO";
  CEP: string;
}
export interface ContatoType {
  Telefone: string;
  Email?: string;
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "ResumoAcademicoType".
 */
export interface ResumoAcademicoType {
  CRA: string;
  TotalCreditosConcluidos: string;
  Observacoes?: string;
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "AssinaturaType".
 */
export interface AssinaturaType {
  NomeAssinador: string;
  Cargo: string;
  Data: string;
  AssinaturaDigital: string;
}
