/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "DisciplinaType".
 */
export type DisciplinaType = {
  Nome: string;
  Codigo: string;
  Creditos: string;
  CargaHoraria: string;
  Frequencia?: string;
  Situacao: "Aprovado" | "Reprovado" | "Recuperação" | "Matriculado" | "Dispensado";
  Comentarios?: string;
} & DisciplinaType1;
export type DisciplinaType1 =
  | {
      Nota: string;
    }
  | {
      NotaEscala: "A" | "B" | "C" | "D" | "E" | "F";
    };

export interface BoletimTypesSchema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "InstituicaoType".
 */
export interface InstituicaoType {
  Nome: string;
  CNPJ: string;
  Unidade?: string;
  Endereco: EnderecoType;
  Contato?: ContatoType;
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "EnderecoType".
 */
export interface EnderecoType {
  Logradouro: string;
  Numero: string;
  Complemento?: string;
  Bairro: string;
  Cidade: string;
  UF:
    | "AC"
    | "AL"
    | "AM"
    | "AP"
    | "BA"
    | "CE"
    | "DF"
    | "ES"
    | "GO"
    | "MA"
    | "MG"
    | "MS"
    | "MT"
    | "PA"
    | "PB"
    | "PE"
    | "PI"
    | "PR"
    | "RJ"
    | "RN"
    | "RO"
    | "RR"
    | "RS"
    | "SC"
    | "SE"
    | "SP"
    | "TO";
  CEP: string;
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "ContatoType".
 */
export interface ContatoType {
  Telefone: string;
  Email?: string;
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "EstudanteType".
 */
export interface EstudanteType {
  ID: string;
  Nome: string;
  CPF: string;
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "CursoType".
 */
export interface CursoType {
  Nome: string;
  Codigo: string;
  Nivel?: "Bacharelado" | "Licenciatura" | "Tecnólogo";
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "PeriodoType".
 */
export interface PeriodoType {
  Codigo: string;
  Inicio: string;
  Fim: string;
  /**
   * @minItems 1
   */
  Disciplinas: [
    {
      Disciplina: DisciplinaType;
    },
    ...{
      Disciplina: DisciplinaType;
    }[]
  ];
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "ResumoAcademicoType".
 */
export interface ResumoAcademicoType {
  CRA: string;
  TotalCreditosConcluidos: string;
  Observacoes?: string;
}
/**
 * This interface was referenced by `BoletimTypesSchema`'s JSON-Schema
 * via the `definition` "AssinaturaType".
 */
export interface AssinaturaType {
  NomeAssinador: string;
  Cargo: string;
  Data: string;
  AssinaturaDigital: string;
}
