/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `AcademicoTypesSchema`'s JSON-Schema
 * via the `definition` "DisciplinaType".
 */
export type DisciplinaType = {
  Nome: string;
  Codigo: string;
  Creditos: string;
  CargaHoraria: string;
  Frequencia?: string;
  Situacao: "Aprovado" | "Reprovado" | "Recuperação" | "Matriculado" | "Dispensado";
  Comentarios?: string;
  Nota?: unknown;
  NotaEscala?: unknown;
} & DisciplinaType1;
export type DisciplinaType1 =
  | {
      Nota: string;
      [k: string]: unknown;
    }
  | {
      NotaEscala: "A" | "B" | "C" | "D" | "E" | "F";
      [k: string]: unknown;
    };
/**
 * @minItems 1
 *
 * This interface was referenced by `AcademicoTypesSchema`'s JSON-Schema
 * via the `definition` "DisciplinaArrayType".
 */
export type DisciplinaArrayType = [
  {
    Disciplina: DisciplinaType;
  },
  ...{
    Disciplina: DisciplinaType;
  }[]
];
/**
 * @minItems 1
 *
 * This interface was referenced by `AcademicoTypesSchema`'s JSON-Schema
 * via the `definition` "PeriodoArrayType".
 */
export type PeriodoArrayType = [
  {
    Periodo: PeriodoType;
  },
  ...{
    Periodo: PeriodoType;
  }[]
];

export interface AcademicoTypesSchema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AcademicoTypesSchema`'s JSON-Schema
 * via the `definition` "CursoType".
 */
export interface CursoType {
  Nome: string;
  Codigo: string;
  Nivel?: "Bacharelado" | "Licenciatura" | "Tecnólogo";
}
/**
 * This interface was referenced by `AcademicoTypesSchema`'s JSON-Schema
 * via the `definition` "PeriodoType".
 */
export interface PeriodoType {
  Codigo: string;
  Inicio: string;
  Fim: string;
  Disciplinas: DisciplinaArrayType;
}
