/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LocalizacaoTypesSchema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `LocalizacaoTypesSchema`'s JSON-Schema
 * via the `definition` "EnderecoType".
 */
export interface EnderecoType {
  Logradouro: string;
  Numero: string;
  Complemento?: string;
  Bairro: string;
  Cidade: string;
  UF:
    | "AC"
    | "AL"
    | "AM"
    | "AP"
    | "BA"
    | "CE"
    | "DF"
    | "ES"
    | "GO"
    | "MA"
    | "MG"
    | "MS"
    | "MT"
    | "PA"
    | "PB"
    | "PE"
    | "PI"
    | "PR"
    | "RJ"
    | "RN"
    | "RO"
    | "RR"
    | "RS"
    | "SC"
    | "SE"
    | "SP"
    | "TO";
  CEP: string;
}
/**
 * This interface was referenced by `LocalizacaoTypesSchema`'s JSON-Schema
 * via the `definition` "ContatoType".
 */
export interface ContatoType {
  Telefone: string;
  Email?: string;
}
