/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PessoalTypesSchema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `PessoalTypesSchema`'s JSON-Schema
 * via the `definition` "EstudanteType".
 */
export interface EstudanteType {
  ID: string;
  Nome: string;
  CPF: string;
}
