/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "StringType".
 */
export type StringType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "NumberType".
 */
export type NumberType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "DecimalType".
 */
export type DecimalType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "DateType".
 */
export type DateType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "IDType".
 */
export type IDType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "Base64BinaryType".
 */
export type Base64BinaryType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "PhoneType".
 */
export type PhoneType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "CPFType".
 */
export type CPFType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "CNPJType".
 */
export type CNPJType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "CEPType".
 */
export type CEPType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "UFType".
 */
export type UFType =
  | "AC"
  | "AL"
  | "AM"
  | "AP"
  | "BA"
  | "CE"
  | "DF"
  | "ES"
  | "GO"
  | "MA"
  | "MG"
  | "MS"
  | "MT"
  | "PA"
  | "PB"
  | "PE"
  | "PI"
  | "PR"
  | "RJ"
  | "RN"
  | "RO"
  | "RR"
  | "RS"
  | "SC"
  | "SE"
  | "SP"
  | "TO";
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "PercentType".
 */
export type PercentType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "NotaType".
 */
export type NotaType = string;
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "SituacaoType".
 */
export type SituacaoType = "Aprovado" | "Reprovado" | "Recuperação" | "Matriculado" | "Dispensado";
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "EscalaConceitoType".
 */
export type EscalaConceitoType = "A" | "B" | "C" | "D" | "E" | "F";
/**
 * This interface was referenced by `SimpleTypesSchema`'s JSON-Schema
 * via the `definition` "NivelCursoType".
 */
export type NivelCursoType = "Bacharelado" | "Licenciatura" | "Tecnólogo";

export interface SimpleTypesSchema {
  [k: string]: unknown;
}
